export interface SeedCompany {
  name: string;
  category: "company" | "startup" | "remote" | "visa_remote" | "india_tech";
  portal_url: string;
  location?: string;
  job_title?: string;
  actively_hiring?: boolean;
  visa_sponsorship?: boolean;
}

export const TOP_COMPANIES: SeedCompany[] = [
  // --- TOP 100 TECH COMPANIES ---
  { name: "Google", category: "company", portal_url: "https://careers.google.com", location: "Mountain View, CA / Remote" },
  { name: "Microsoft", category: "company", portal_url: "https://careers.microsoft.com", location: "Redmond, WA / Remote" },
  { name: "Apple", category: "company", portal_url: "https://www.apple.com/careers", location: "Cupertino, CA" },
  { name: "Amazon", category: "company", portal_url: "https://www.amazon.jobs", location: "Seattle, WA / Remote" },
  { name: "Meta", category: "company", portal_url: "https://www.metacareers.com", location: "Menlo Park, CA / Remote" },
  { name: "Netflix", category: "company", portal_url: "https://jobs.netflix.com", location: "Los Gatos, CA / Remote" },
  { name: "Nvidia", category: "company", portal_url: "https://www.nvidia.com/en-us/about-nvidia/careers/", location: "Santa Clara, CA" },
  { name: "Adobe", category: "company", portal_url: "https://www.adobe.com/careers.html", location: "San Jose, CA / Remote" },
  { name: "Salesforce", category: "company", portal_url: "https://www.salesforce.com/company/careers/", location: "San Francisco, CA / Remote" },
  { name: "Oracle", category: "company", portal_url: "https://www.oracle.com/careers/", location: "Austin, TX / Remote" },
  { name: "IBM", category: "company", portal_url: "https://www.ibm.com/careers", location: "Armonk, NY / Remote" },
  { name: "Cisco", category: "company", portal_url: "https://jobs.cisco.com", location: "San Jose, CA / Remote" },
  { name: "Intel", category: "company", portal_url: "https://jobs.intel.com", location: "Santa Clara, CA / Remote" },
  { name: "AMD", category: "company", portal_url: "https://www.amd.com/en/corporate/careers.html", location: "Santa Clara, CA / Remote" },
  { name: "Qualcomm", category: "company", portal_url: "https://www.qualcomm.com/company/careers", location: "San Diego, CA / Remote" },
  { name: "Uber", category: "company", portal_url: "https://www.uber.com/us/en/careers/", location: "San Francisco, CA / Remote" },
  { name: "Airbnb", category: "company", portal_url: "https://careers.airbnb.com", location: "San Francisco, CA / Remote" },
  { name: "Lyft", category: "company", portal_url: "https://www.lyft.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Spotify", category: "company", portal_url: "https://www.lifeatspotify.com", location: "Stockholm / NYC / Remote" },
  { name: "Tesla", category: "company", portal_url: "https://www.tesla.com/careers", location: "Palo Alto, CA / Austin, TX" },
  { name: "Block (Square)", category: "company", portal_url: "https://block.xyz/careers", location: "San Francisco, CA / Remote" },
  { name: "PayPal", category: "company", portal_url: "https://crafted.paypal.com/careers", location: "San Jose, CA / Remote" },
  { name: "Shopify", category: "company", portal_url: "https://www.shopify.com/careers", location: "Ottawa, ON / Remote" },
  { name: "Snowflake", category: "company", portal_url: "https://www.snowflake.com/careers/", location: "Bozeman, MT / Remote" },
  { name: "Databricks", category: "company", portal_url: "https://www.databricks.com/company/careers", location: "San Francisco, CA / Remote", actively_hiring: true },
  { name: "Palantir", category: "company", portal_url: "https://www.palantir.com/careers/", location: "Denver, CO / NYC / Remote" },
  { name: "Atlassian", category: "company", portal_url: "https://www.atlassian.com/company/careers", location: "Sydney / SF / Remote" },
  { name: "Workday", category: "company", portal_url: "https://www.workday.com/en-us/company/careers.html", location: "Pleasanton, CA / Remote" },
  { name: "ServiceNow", category: "company", portal_url: "https://www.servicenow.com/company/careers.html", location: "Santa Clara, CA / Remote" },
  { name: "Twilio", category: "company", portal_url: "https://www.twilio.com/en-us/company/jobs", location: "San Francisco, CA / Remote" },
  { name: "Cloudflare", category: "company", portal_url: "https://www.cloudflare.com/careers/", location: "San Francisco, CA / Remote", actively_hiring: true },
  { name: "Datadog", category: "company", portal_url: "https://www.datadoghq.com/careers/", location: "New York, NY / Remote" },
  { name: "MongoDB", category: "company", portal_url: "https://www.mongodb.com/careers", location: "New York, NY / Remote" },
  { name: "CrowdStrike", category: "company", portal_url: "https://www.crowdstrike.com/careers/", location: "Austin, TX / Remote" },
  { name: "Palo Alto Networks", category: "company", portal_url: "https://jobs.paloaltonetworks.com", location: "Santa Clara, CA / Remote" },
  { name: "Okta", category: "company", portal_url: "https://www.okta.com/company/careers/", location: "San Francisco, CA / Remote" },
  { name: "Splunk", category: "company", portal_url: "https://www.splunk.com/en_us/careers.html", location: "San Francisco, CA / Remote" },
  { name: "HashiCorp", category: "company", portal_url: "https://www.hashicorp.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Fastly", category: "company", portal_url: "https://www.fastly.com/careers", location: "San Francisco, CA / Remote" },
  { name: "GitLab", category: "company", portal_url: "https://about.gitlab.com/jobs/", location: "100% Remote" },
  { name: "GitHub", category: "company", portal_url: "https://github.com/about/careers", location: "San Francisco, CA / Remote" },
  { name: "Zoom", category: "company", portal_url: "https://careers.zoom.us", location: "San Jose, CA / Remote" },
  { name: "Slack", category: "company", portal_url: "https://slack.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Pinterest", category: "company", portal_url: "https://www.pinterestcareers.com", location: "San Francisco, CA / Remote" },
  { name: "Snap Inc.", category: "company", portal_url: "https://careers.snap.com", location: "Santa Monica, CA / Remote" },
  { name: "Reddit", category: "company", portal_url: "https://www.redditinc.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Robinhood", category: "company", portal_url: "https://robinhood.com/us/en/careers/", location: "Menlo Park, CA / Remote" },
  { name: "Coinbase", category: "company", portal_url: "https://www.coinbase.com/careers", location: "100% Remote" },
  { name: "DoorDash", category: "company", portal_url: "https://careers.doordash.com", location: "San Francisco, CA / Remote" },
  { name: "Instacart", category: "company", portal_url: "https://instacart.careers", location: "San Francisco, CA / Remote" },
  { name: "eBay", category: "company", portal_url: "https://careers.ebayinc.com", location: "San Jose, CA / Remote" },
  { name: "Etsy", category: "company", portal_url: "https://careers.etsy.com", location: "Brooklyn, NY / Remote" },
  { name: "MercadoLibre", category: "company", portal_url: "https://careers-mercadolibre.com", location: "Buenos Aires / Remote" },
  { name: "Sea Limited", category: "company", portal_url: "https://www.seagroup.com/careers", location: "Singapore / Remote" },
  { name: "Grab", category: "company", portal_url: "https://grab.careers", location: "Singapore / Remote" },
  { name: "GoTo", category: "company", portal_url: "https://gotocompany.com/careers", location: "Jakarta / Remote" },
  { name: "Booking.com", category: "company", portal_url: "https://jobs.booking.com", location: "Amsterdam / Remote" },
  { name: "Expedia Group", category: "company", portal_url: "https://www.expediagroup.com/careers/", location: "Seattle, WA / Remote" },
  { name: "TripAdvisor", category: "company", portal_url: "https://careers.tripadvisor.com", location: "Needham, MA / Remote" },
  { name: "HubSpot", category: "company", portal_url: "https://www.hubspot.com/careers", location: "Cambridge, MA / Remote" },
  { name: "Zscaler", category: "company", portal_url: "https://www.zscaler.com/careers", location: "San Jose, CA / Remote" },
  { name: "SentinelOne", category: "company", portal_url: "https://www.sentinelone.com/careers/", location: "Mountain View, CA / Remote" },
  { name: "Confluent", category: "company", portal_url: "https://www.confluent.io/careers/", location: "Mountain View, CA / Remote" },
  { name: "Elastic", category: "company", portal_url: "https://www.elastic.co/careers/", location: "100% Remote" },
  { name: "VMware", category: "company", portal_url: "https://careers.vmware.com", location: "Palo Alto, CA / Remote" },
  { name: "Broadcom", category: "company", portal_url: "https://www.broadcom.com/company/careers", location: "San Jose, CA / Remote" },
  { name: "Dell Technologies", category: "company", portal_url: "https://jobs.dell.com", location: "Round Rock, TX / Remote" },
  { name: "HP Inc.", category: "company", portal_url: "https://jobs.hp.com", location: "Palo Alto, CA / Remote" },
  { name: "Lenovo", category: "company", portal_url: "https://jobs.lenovo.com", location: "Morrisville, NC / Remote" },
  { name: "Sony", category: "company", portal_url: "https://www.sony.com/en/SonyInfo/Careers/", location: "Tokyo / San Mateo, CA" },
  { name: "Samsung", category: "company", portal_url: "https://www.samsung.com/us/careers/", location: "Seoul / Mountain View, CA" },
  { name: "LG Electronics", category: "company", portal_url: "https://www.lg.com/global/careers", location: "Seoul / Englewood Cliffs, NJ" },
  { name: "Siemens", category: "company", portal_url: "https://jobs.siemens.com", location: "Munich / Remote" },
  { name: "SAP", category: "company", portal_url: "https://jobs.sap.com", location: "Walldorf / Remote" },
  { name: "ASML", category: "company", portal_url: "https://www.asml.com/en/careers", location: "Veldhoven / San Jose, CA" },
  { name: "Infosys", category: "company", portal_url: "https://www.infosys.com/careers/", location: "Bengaluru / Remote" },
  { name: "TCS", category: "company", portal_url: "https://www.tcs.com/careers", location: "Mumbai / Remote" },
  { name: "Wipro", category: "company", portal_url: "https://careers.wipro.com", location: "Bengaluru / Remote" },
  { name: "HCLTech", category: "company", portal_url: "https://www.hcltech.com/careers", location: "Noida / Remote" },
  { name: "Tech Mahindra", category: "company", portal_url: "https://www.techmahindra.com/en-in/careers/", location: "Pune / Remote" },
  { name: "Cognizant", category: "company", portal_url: "https://careers.cognizant.com", location: "Teaneck, NJ / Remote" },
  { name: "Accenture", category: "company", portal_url: "https://www.accenture.com/us-en/careers", location: "Dublin / Global" },
  { name: "Capgemini", category: "company", portal_url: "https://www.capgemini.com/careers/", location: "Paris / Remote" },
  { name: "EPAM Systems", category: "company", portal_url: "https://www.epam.com/careers", location: "Newtown, PA / Remote" },
  { name: "Thoughtworks", category: "company", portal_url: "https://www.thoughtworks.com/careers", location: "Chicago, IL / Remote" },
  { name: "Stripe", category: "company", portal_url: "https://stripe.com/jobs", location: "San Francisco, CA / Remote", actively_hiring: true },
  { name: "Plaid", category: "company", portal_url: "https://plaid.com/careers/", location: "San Francisco, CA / Remote" },
  { name: "Brex", category: "company", portal_url: "https://www.brex.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Ramp", category: "company", portal_url: "https://ramp.com/careers", location: "New York, NY / Remote" },
  { name: "Toast", category: "company", portal_url: "https://pos.toasttab.com/careers", location: "Boston, MA / Remote" },
  { name: "Affirm", category: "company", portal_url: "https://www.affirm.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Chime", category: "company", portal_url: "https://www.chime.com/careers/", location: "San Francisco, CA / Remote" },
  { name: "Revolut", category: "company", portal_url: "https://www.revolut.com/careers/", location: "London / Remote" },
  { name: "Monzo", category: "company", portal_url: "https://monzo.com/careers/", location: "London / Remote" },
  { name: "Klarna", category: "company", portal_url: "https://www.klarna.com/careers/", location: "Stockholm / Remote" },
  { name: "Wise", category: "company", portal_url: "https://wise.jobs", location: "London / Remote" },
  { name: "SoFi", category: "company", portal_url: "https://www.sofi.com/careers/", location: "San Francisco, CA / Remote" },
  { name: "Intuit", category: "company", portal_url: "https://jobs.intuit.com", location: "Mountain View, CA / Remote" },
  { name: "Autodesk", category: "company", portal_url: "https://www.autodesk.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Synopsys", category: "company", portal_url: "https://www.synopsys.com/company/careers.html", location: "Sunnyvale, CA / Remote" },

  // --- TOP 100 TECH STARTUPS ---
  { name: "OpenAI", category: "startup", portal_url: "https://openai.com/careers", location: "San Francisco, CA", actively_hiring: true },
  { name: "Anthropic", category: "startup", portal_url: "https://anthropic.com/careers", location: "San Francisco, CA / Seattle, WA", actively_hiring: true },
  { name: "Midjourney", category: "startup", portal_url: "https://www.midjourney.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Perplexity AI", category: "startup", portal_url: "https://www.perplexity.ai/careers", location: "San Francisco, CA", actively_hiring: true },
  { name: "Mistral AI", category: "startup", portal_url: "https://mistral.ai/careers/", location: "Paris / Remote" },
  { name: "Cohere", category: "startup", portal_url: "https://cohere.com/careers", location: "Toronto / SF / Remote" },
  { name: "ElevenLabs", category: "startup", portal_url: "https://elevenlabs.io/careers", location: "New York, NY / Remote" },
  { name: "Scale AI", category: "startup", portal_url: "https://scale.com/careers", location: "San Francisco, CA", actively_hiring: true },
  { name: "Hugging Face", category: "startup", portal_url: "https://huggingface.co/jobs", location: "NYC / Paris / Remote" },
  { name: "Runway", category: "startup", portal_url: "https://runwayml.com/careers", location: "New York, NY / Remote" },
  { name: "Character.AI", category: "startup", portal_url: "https://beta.character.ai/careers", location: "Palo Alto, CA" },
  { name: "Synthesia", category: "startup", portal_url: "https://www.synthesia.io/careers", location: "London / Remote" },
  { name: "Cursor (Anysphere)", category: "startup", portal_url: "https://www.cursor.com/careers", location: "San Francisco, CA", actively_hiring: true },
  { name: "Replit", category: "startup", portal_url: "https://replit.com/site/careers", location: "San Francisco, CA / Remote" },
  { name: "Supabase", category: "startup", portal_url: "https://supabase.com/careers", location: "100% Remote", actively_hiring: true },
  { name: "Vercel", category: "startup", portal_url: "https://vercel.com/careers", location: "San Francisco, CA / Remote", actively_hiring: true },
  { name: "Netlify", category: "startup", portal_url: "https://www.netlify.com/careers/", location: "100% Remote" },
  { name: "Railway", category: "startup", portal_url: "https://railway.app/careers", location: "San Francisco, CA / Remote" },
  { name: "Render", category: "startup", portal_url: "https://render.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Fly.io", category: "startup", portal_url: "https://fly.io/jobs", location: "100% Remote" },
  { name: "Neon", category: "startup", portal_url: "https://neon.tech/careers", location: "100% Remote" },
  { name: "PlanetScale", category: "startup", portal_url: "https://planetscale.com/careers", location: "100% Remote" },
  { name: "Cockroach Labs", category: "startup", portal_url: "https://www.cockroachlabs.com/careers/", location: "New York, NY / Remote" },
  { name: "Pinecone", category: "startup", portal_url: "https://www.pinecone.io/careers/", location: "New York, NY / Remote" },
  { name: "Qdrant", category: "startup", portal_url: "https://qdrant.tech/careers/", location: "Berlin / Remote" },
  { name: "Chroma", category: "startup", portal_url: "https://www.trychroma.com/careers", location: "San Francisco, CA" },
  { name: "Weaviate", category: "startup", portal_url: "https://weaviate.io/company/careers", location: "100% Remote" },
  { name: "LangChain", category: "startup", portal_url: "https://www.langchain.com/careers", location: "San Francisco, CA" },
  { name: "LlamaIndex", category: "startup", portal_url: "https://www.llamaindex.ai/careers", location: "San Francisco, CA" },
  { name: "Modal", category: "startup", portal_url: "https://modal.com/careers", location: "New York, NY / Remote" },
  { name: "Baseten", category: "startup", portal_url: "https://www.baseten.co/careers/", location: "San Francisco, CA" },
  { name: "Together AI", category: "startup", portal_url: "https://www.together.ai/careers", location: "San Francisco, CA" },
  { name: "Groq", category: "startup", portal_url: "https://groq.com/careers/", location: "Mountain View, CA / Remote" },
  { name: "Cerebras", category: "startup", portal_url: "https://cerebras.ai/careers", location: "Sunnyvale, CA" },
  { name: "Anyscale", category: "startup", portal_url: "https://www.anyscale.com/careers", location: "San Francisco, CA" },
  { name: "Weights & Biases", category: "startup", portal_url: "https://wandb.ai/site/careers", location: "San Francisco, CA / Remote" },
  { name: "PostHog", category: "startup", portal_url: "https://posthog.com/careers", location: "100% Remote" },
  { name: "Mixpanel", category: "startup", portal_url: "https://mixpanel.com/jobs/", location: "San Francisco, CA / Remote" },
  { name: "Amplitude", category: "startup", portal_url: "https://amplitude.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Segment", category: "startup", portal_url: "https://segment.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Census", category: "startup", portal_url: "https://www.getcensus.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Hightouch", category: "startup", portal_url: "https://hightouch.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Resend", category: "startup", portal_url: "https://resend.com/careers", location: "100% Remote" },
  { name: "Loops", category: "startup", portal_url: "https://loops.so/careers", location: "100% Remote" },
  { name: "Novu", category: "startup", portal_url: "https://novu.co/careers", location: "100% Remote" },
  { name: "Clerk", category: "startup", portal_url: "https://clerk.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Stytch", category: "startup", portal_url: "https://stytch.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Descope", category: "startup", portal_url: "https://www.descope.com/careers", location: "Los Altos, CA / Remote" },
  { name: "WorkOS", category: "startup", portal_url: "https://workos.com/careers", location: "100% Remote" },
  { name: "Checkly", category: "startup", portal_url: "https://www.checklyhq.com/jobs/", location: "100% Remote" },
  { name: "Better Stack", category: "startup", portal_url: "https://betterstack.com/careers", location: "Prague / Remote" },
  { name: "Sentry", category: "startup", portal_url: "https://sentry.io/careers/", location: "San Francisco, CA / Remote" },
  { name: "Axiom", category: "startup", portal_url: "https://axiom.co/careers", location: "100% Remote" },
  { name: "DataStax", category: "startup", portal_url: "https://www.datastax.com/company/careers", location: "Santa Clara, CA / Remote" },
  { name: "Temporal", category: "startup", portal_url: "https://temporal.io/careers", location: "Seattle, WA / Remote" },
  { name: "Trigger.dev", category: "startup", portal_url: "https://trigger.dev/careers", location: "100% Remote" },
  { name: "Inngest", category: "startup", portal_url: "https://www.inngest.com/careers", location: "100% Remote" },
  { name: "Deel", category: "startup", portal_url: "https://www.deel.com/careers", location: "100% Remote" },
  { name: "Rippling", category: "startup", portal_url: "https://www.rippling.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Gusto", category: "startup", portal_url: "https://gusto.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Mercury", category: "startup", portal_url: "https://mercury.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Flexport", category: "startup", portal_url: "https://www.flexport.com/careers/", location: "San Francisco, CA / Remote" },
  { name: "Carta", category: "startup", portal_url: "https://carta.com/careers/", location: "San Francisco, CA / Remote" },
  { name: "Pulley", category: "startup", portal_url: "https://pulley.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Substack", category: "startup", portal_url: "https://substack.com/jobs", location: "San Francisco, CA / Remote" },
  { name: "Medium", category: "startup", portal_url: "https://medium.com/jobs", location: "San Francisco, CA / Remote" },
  { name: "Notion", category: "startup", portal_url: "https://www.notion.so/careers", location: "San Francisco, CA / Remote" },
  { name: "Figma", category: "startup", portal_url: "https://www.figma.com/careers/", location: "San Francisco, CA / Remote" },
  { name: "Linear", category: "startup", portal_url: "https://linear.app/careers", location: "San Francisco, CA / Remote" },
  { name: "Raycast", category: "startup", portal_url: "https://www.raycast.com/jobs", location: "London / Remote" },
  { name: "Framer", category: "startup", portal_url: "https://www.framer.com/careers/", location: "Amsterdam / Remote" },
  { name: "Webflow", category: "startup", portal_url: "https://webflow.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Retool", category: "startup", portal_url: "https://retool.com/careers", location: "San Francisco, CA" },
  { name: "Builder.io", category: "startup", portal_url: "https://www.builder.io/careers", location: "100% Remote" },
  { name: "Mutiny", category: "startup", portal_url: "https://www.mutinyhq.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Postman", category: "startup", portal_url: "https://www.postman.com/company/careers/", location: "San Francisco, CA / Remote" },
  { name: "Kong", category: "startup", portal_url: "https://konghq.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Sourcegraph", category: "startup", portal_url: "https://about.sourcegraph.com/jobs", location: "100% Remote" },
  { name: "Codeium", category: "startup", portal_url: "https://codeium.com/careers", location: "Mountain View, CA" },
  { name: "Tabnine", category: "startup", portal_url: "https://www.tabnine.com/careers", location: "Tel Aviv / Remote" },
  { name: "Continue", category: "startup", portal_url: "https://www.continue.dev/careers", location: "San Francisco, CA" },
  { name: "Warp", category: "startup", portal_url: "https://www.warp.dev/careers", location: "New York, NY" },
  { name: "Arc (The Browser Company)", category: "startup", portal_url: "https://thebrowser.company/careers", location: "New York, NY" },
  { name: "Loom", category: "startup", portal_url: "https://www.loom.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Pitch", category: "startup", portal_url: "https://pitch.com/careers", location: "Berlin / Remote" },
  { name: "Coda", category: "startup", portal_url: "https://coda.io/careers", location: "Mountain View, CA / Remote" },
  { name: "Slite", category: "startup", portal_url: "https://slite.com/careers", location: "100% Remote" },
  { name: "Readwise", category: "startup", portal_url: "https://readwise.io/careers", location: "100% Remote" },
  { name: "Superhuman", category: "startup", portal_url: "https://superhuman.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Shortwave", category: "startup", portal_url: "https://www.shortwave.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Cal.com", category: "startup", portal_url: "https://cal.com/careers", location: "100% Remote" },
  { name: "Dub.co", category: "startup", portal_url: "https://dub.co/careers", location: "100% Remote" },
  { name: "Harvey AI", category: "startup", portal_url: "https://www.harvey.ai/careers", location: "San Francisco, CA" },
  { name: "Ironclad", category: "startup", portal_url: "https://ironcladapp.com/careers/", location: "San Francisco, CA / Remote" },
  { name: "Casetext", category: "startup", portal_url: "https://casetext.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Shield AI", category: "startup", portal_url: "https://shield.ai/careers", location: "San Diego, CA" },
  { name: "Anduril", category: "startup", portal_url: "https://www.anduril.com/careers", location: "Costa Mesa, CA" },
  { name: "Skydio", category: "startup", portal_url: "https://www.skydio.com/careers", location: "San Mateo, CA" },
  { name: "Astranis", category: "startup", portal_url: "https://www.astranis.com/careers", location: "San Francisco, CA" },
  { name: "Relativity Space", category: "startup", portal_url: "https://www.relativityspace.com/careers", location: "Long Beach, CA" },

  // --- TOP 100 REMOTE-FIRST COMPANIES ---
  { name: "Automattic", category: "remote", portal_url: "https://automattic.com/work-with-us/", location: "100% Remote Worldwide" },
  { name: "Zapier", category: "remote", portal_url: "https://zapier.com/jobs", location: "100% Remote Worldwide" },
  { name: "Buffer", category: "remote", portal_url: "https://buffer.com/journey", location: "100% Remote Worldwide" },
  { name: "Canonical", category: "remote", portal_url: "https://canonical.com/careers", location: "100% Remote Worldwide" },
  { name: "Doist", category: "remote", portal_url: "https://doist.com/careers", location: "100% Remote Worldwide" },
  { name: "DuckDuckGo", category: "remote", portal_url: "https://duckduckgo.com/hiring", location: "100% Remote Worldwide" },
  { name: "37signals", category: "remote", portal_url: "https://37signals.com/jobs", location: "100% Remote Worldwide" },
  { name: "Ghost", category: "remote", portal_url: "https://ghost.org/careers/", location: "100% Remote Worldwide" },
  { name: "Customer.io", category: "remote", portal_url: "https://customer.io/careers/", location: "100% Remote Worldwide" },
  { name: "Toggl", category: "remote", portal_url: "https://toggl.com/jobs/", location: "100% Remote Worldwide" },
  { name: "InVision", category: "remote", portal_url: "https://www.invisionapp.com/careers", location: "100% Remote Worldwide" },
  { name: "Kraken", category: "remote", portal_url: "https://www.kraken.com/careers", location: "100% Remote Worldwide" },
  { name: "Chainlink Labs", category: "remote", portal_url: "https://chainlinklabs.com/careers", location: "100% Remote Worldwide" },
  { name: "Consensys", category: "remote", portal_url: "https://consensys.io/careers", location: "100% Remote Worldwide" },
  { name: "Uniswap", category: "remote", portal_url: "https://uniswap.org/careers", location: "100% Remote Worldwide" },
  { name: "OpenSea", category: "remote", portal_url: "https://opensea.io/careers", location: "100% Remote Worldwide" },
  { name: "Protocol Labs", category: "remote", portal_url: "https://protocol.ai/join/", location: "100% Remote Worldwide" },
  { name: "Matter Labs", category: "remote", portal_url: "https://matter-labs.io/careers", location: "100% Remote Worldwide" },
  { name: "Solana Labs", category: "remote", portal_url: "https://solana.com/careers", location: "100% Remote Worldwide" },
  { name: "Polygon Technology", category: "remote", portal_url: "https://polygon.technology/careers", location: "100% Remote Worldwide" },
  { name: "Alchemy", category: "remote", portal_url: "https://www.alchemy.com/careers", location: "100% Remote Worldwide" },
  { name: "Fireblocks", category: "remote", portal_url: "https://www.fireblocks.com/careers/", location: "100% Remote Worldwide" },
  { name: "Anchorage Digital", category: "remote", portal_url: "https://www.anchorage.com/careers", location: "100% Remote Worldwide" },
  { name: "Circle", category: "remote", portal_url: "https://www.circle.com/en/careers", location: "100% Remote Worldwide" },
  { name: "BitGo", category: "remote", portal_url: "https://www.bitgo.com/careers/", location: "100% Remote Worldwide" },
  { name: "Dapper Labs", category: "remote", portal_url: "https://www.dapperlabs.com/careers", location: "100% Remote Worldwide" },
  { name: "Ripple", category: "remote", portal_url: "https://ripple.com/careers/", location: "100% Remote Worldwide" },
  { name: "Gemini", category: "remote", portal_url: "https://www.gemini.com/careers", location: "100% Remote Worldwide" },
  { name: "Blockdaemon", category: "remote", portal_url: "https://blockdaemon.com/careers/", location: "100% Remote Worldwide" },
  { name: "TaxBit", category: "remote", portal_url: "https://taxbit.com/careers", location: "100% Remote Worldwide" },
  { name: "Offchain Labs", category: "remote", portal_url: "https://offchainlabs.com/careers", location: "100% Remote Worldwide" },
  { name: "Ava Labs", category: "remote", portal_url: "https://www.avalabs.org/careers", location: "100% Remote Worldwide" },
  { name: "Mysten Labs", category: "remote", portal_url: "https://mystenlabs.com/careers", location: "100% Remote Worldwide" },
  { name: "Aptos Labs", category: "remote", portal_url: "https://aptoslabs.com/careers", location: "100% Remote Worldwide" },
  { name: "StarkWare", category: "remote", portal_url: "https://starkware.co/careers/", location: "100% Remote Worldwide" },
  { name: "Optimism", category: "remote", portal_url: "https://www.optimism.io/careers", location: "100% Remote Worldwide" },
  { name: "Celestia", category: "remote", portal_url: "https://celestia.org/careers", location: "100% Remote Worldwide" },
  { name: "Monad Labs", category: "remote", portal_url: "https://www.monad.xyz/careers", location: "100% Remote Worldwide" },
  { name: "Berachain", category: "remote", portal_url: "https://www.berachain.com/careers", location: "100% Remote Worldwide" },
  { name: "Flashbots", category: "remote", portal_url: "https://flashbots.net/jobs", location: "100% Remote Worldwide" },
  { name: "Paradigm", category: "remote", portal_url: "https://www.paradigm.xyz/careers", location: "100% Remote Worldwide" },
  { name: "a16z crypto", category: "remote", portal_url: "https://a16z.com/careers/", location: "100% Remote Worldwide" },
  { name: "Electric Capital", category: "remote", portal_url: "https://www.electriccapital.com/careers", location: "100% Remote Worldwide" },
  { name: "Dragonfly", category: "remote", portal_url: "https://www.dragonfly.xyz/careers", location: "100% Remote Worldwide" },
  { name: "Polychain Capital", category: "remote", portal_url: "https://polychain.capital/careers", location: "100% Remote Worldwide" },
  { name: "Multicoin Capital", category: "remote", portal_url: "https://multicoin.capital/careers", location: "100% Remote Worldwide" },
  { name: "Pantera Capital", category: "remote", portal_url: "https://panteracapital.com/careers", location: "100% Remote Worldwide" },
  { name: "Framework Ventures", category: "remote", portal_url: "https://framework.ventures/careers", location: "100% Remote Worldwide" },
  { name: "Variant Fund", category: "remote", portal_url: "https://variant.fund/careers", location: "100% Remote Worldwide" },
  { name: "Hack VC", category: "remote", portal_url: "https://hack.vc/careers", location: "100% Remote Worldwide" },
  { name: "CoinShares", category: "remote", portal_url: "https://coinshares.com/careers", location: "100% Remote Worldwide" },
  { name: "Wintermute", category: "remote", portal_url: "https://www.wintermute.com/careers", location: "100% Remote Worldwide" },
  { name: "Cumberland", category: "remote", portal_url: "https://cumberland.io/careers", location: "100% Remote Worldwide" },
  { name: "Jump Crypto", category: "remote", portal_url: "https://jumpcrypto.com/careers", location: "100% Remote Worldwide" },
  { name: "Amber Group", category: "remote", portal_url: "https://www.ambergroup.io/careers", location: "100% Remote Worldwide" },
  { name: "GSR", category: "remote", portal_url: "https://www.gsr.io/careers", location: "100% Remote Worldwide" },
  { name: "B2C2", category: "remote", portal_url: "https://www.b2c2.com/careers", location: "100% Remote Worldwide" },
  { name: "Galaxy Digital", category: "remote", portal_url: "https://www.galaxy.com/careers", location: "100% Remote Worldwide" },
  { name: "Bitpanda", category: "remote", portal_url: "https://www.bitpanda.com/en/careers", location: "100% Remote Worldwide" },
  { name: "Trade Republic", category: "remote", portal_url: "https://traderepublic.com/en-de/careers", location: "100% Remote Worldwide" },
  { name: "N26", category: "remote", portal_url: "https://n26.com/en-eu/careers", location: "100% Remote Worldwide" },
  { name: "Starling Bank", category: "remote", portal_url: "https://www.starlingbank.com/careers/", location: "100% Remote Worldwide" },
  { name: "Bunq", category: "remote", portal_url: "https://www.bunq.com/jobs", location: "100% Remote Worldwide" },
  { name: "OakNorth", category: "remote", portal_url: "https://www.oaknorth.co.uk/careers/", location: "100% Remote Worldwide" },
  { name: "Qonto", category: "remote", portal_url: "https://qonto.com/en/careers", location: "100% Remote Worldwide" },
  { name: "SumUp", category: "remote", portal_url: "https://www.sumup.com/en-us/careers/", location: "100% Remote Worldwide" },
  { name: "Zopa", category: "remote", portal_url: "https://www.zopa.com/careers", location: "100% Remote Worldwide" },
  { name: "Tide", category: "remote", portal_url: "https://www.tide.co/careers/", location: "100% Remote Worldwide" },
  { name: "Soldo", category: "remote", portal_url: "https://www.soldo.com/en-gb/careers/", location: "100% Remote Worldwide" },
  { name: "Pleo", category: "remote", portal_url: "https://www.pleo.io/en/careers", location: "100% Remote Worldwide" },
  { name: "Spendesk", category: "remote", portal_url: "https://www.spendesk.com/en/careers/", location: "100% Remote Worldwide" },
  { name: "Moss", category: "remote", portal_url: "https://getmoss.com/en/careers/", location: "100% Remote Worldwide" },
  { name: "Agicap", category: "remote", portal_url: "https://agicap.com/en/careers/", location: "100% Remote Worldwide" },
  { name: "Pennylane", category: "remote", portal_url: "https://www.pennylane.com/careers", location: "100% Remote Worldwide" },
  { name: "Pigment", category: "remote", portal_url: "https://www.gopigment.com/careers", location: "100% Remote Worldwide" },
  { name: "Anaplan", category: "remote", portal_url: "https://www.anaplan.com/careers/", location: "100% Remote Worldwide" },
  { name: "Adaptive Insights", category: "remote", portal_url: "https://www.adaptiveinsights.com/careers", location: "100% Remote Worldwide" },
  { name: "Planful", category: "remote", portal_url: "https://planful.com/careers/", location: "100% Remote Worldwide" },
  { name: "Vena Solutions", category: "remote", portal_url: "https://www.venasolutions.com/careers", location: "100% Remote Worldwide" },
  { name: "Cube Software", category: "remote", portal_url: "https://www.cube.io/careers", location: "100% Remote Worldwide" },
  { name: "Mosaic", category: "remote", portal_url: "https://www.mosaic.tech/careers", location: "100% Remote Worldwide" },

  // --- VISA SPONSORSHIP & GLOBAL RELOCATION ---
  { name: "Adyen", category: "visa_remote", portal_url: "https://careers.adyen.com", location: "Amsterdam, Netherlands (Visa & Relocation)", visa_sponsorship: true },
  { name: "Delivery Hero", category: "visa_remote", portal_url: "https://careers.deliveryhero.com", location: "Berlin, Germany (Visa & Relocation)", visa_sponsorship: true },
  { name: "Zalando", category: "visa_remote", portal_url: "https://jobs.zalando.com", location: "Berlin, Germany (Visa & Relocation)", visa_sponsorship: true },
  { name: "Personio", category: "visa_remote", portal_url: "https://www.personio.com/careers", location: "Munich, Germany (Visa & Relocation)", visa_sponsorship: true },
  { name: "Bolt", category: "visa_remote", portal_url: "https://bolt.eu/careers/", location: "Tallinn, Estonia (Visa & Relocation)", visa_sponsorship: true },
  { name: "Shopee", category: "visa_remote", portal_url: "https://careers.shopee.sg", location: "Singapore (Visa & Relocation)", visa_sponsorship: true },
  { name: "Rakuten", category: "visa_remote", portal_url: "https://rakuten.careers", location: "Tokyo, Japan (Visa & Relocation)", visa_sponsorship: true },
  { name: "Mercari", category: "visa_remote", portal_url: "https://careers.mercari.com", location: "Tokyo, Japan (Visa & Relocation)", visa_sponsorship: true },
  { name: "LY Corporation (LINE)", category: "visa_remote", portal_url: "https://linecorp.com/en/career/", location: "Tokyo, Japan (Visa & Relocation)", visa_sponsorship: true },
  { name: "Careem", category: "visa_remote", portal_url: "https://www.careem.com/careers/", location: "Dubai, UAE (Visa & Relocation)", visa_sponsorship: true },
  { name: "Talabat", category: "visa_remote", portal_url: "https://www.talabat.com/careers", location: "Dubai, UAE (Visa & Relocation)", visa_sponsorship: true },
  { name: "Canva", category: "visa_remote", portal_url: "https://www.canva.com/careers/", location: "Sydney, Australia (Visa & Relocation)", visa_sponsorship: true },

  // --- TOP TECH & PRODUCT COMPANIES IN INDIA ---
  { name: "Flipkart", category: "india_tech", portal_url: "https://careers.flipkart.com", location: "Bengaluru, India" },
  { name: "Swiggy", category: "india_tech", portal_url: "https://careers.swiggy.com", location: "Bengaluru, India / Remote" },
  { name: "Zomato", category: "india_tech", portal_url: "https://www.zomato.com/careers", location: "Gurgaon, India" },
  { name: "Razorpay", category: "india_tech", portal_url: "https://razorpay.com/jobs/", location: "Bengaluru, India" },
  { name: "PhonePe", category: "india_tech", portal_url: "https://www.phonepe.com/careers/", location: "Bengaluru, India" },
  { name: "Paytm", category: "india_tech", portal_url: "https://paytm.com/careers", location: "Noida, India" },
  { name: "CRED", category: "india_tech", portal_url: "https://cred.club/careers", location: "Bengaluru, India" },
  { name: "Groww", category: "india_tech", portal_url: "https://groww.in/careers", location: "Bengaluru, India" },
  { name: "Zerodha", category: "india_tech", portal_url: "https://zerodha.com/careers", location: "Bengaluru, India" },
  { name: "Meesho", category: "india_tech", portal_url: "https://meesho.io/careers", location: "Bengaluru, India" },
  { name: "Oyo", category: "india_tech", portal_url: "https://www.oyorooms.com/careers", location: "Gurgaon, India" },
  { name: "Ola", category: "india_tech", portal_url: "https://www.olacabs.com/careers", location: "Bengaluru, India" },
  { name: "MakeMyTrip", category: "india_tech", portal_url: "https://careers.makemytrip.com", location: "Gurgaon, India" },
  { name: "InMobi", category: "india_tech", portal_url: "https://www.inmobi.com/company/careers/", location: "Bengaluru, India" },
  { name: "Zepto", category: "india_tech", portal_url: "https://www.zepto.co/careers", location: "Mumbai / Bengaluru, India" },
  { name: "Blinkit", category: "india_tech", portal_url: "https://blinkit.com/careers", location: "Gurgaon, India" },
  { name: "Dream11", category: "india_tech", portal_url: "https://www.dream11.com/careers", location: "Mumbai, India" },
  { name: "Freshworks", category: "india_tech", portal_url: "https://www.freshworks.com/careers/", location: "Chennai / Bengaluru, India" },
  { name: "Hasura", category: "india_tech", portal_url: "https://hasura.io/careers/", location: "Bengaluru, India / Remote" },
  { name: "BrowserStack", category: "india_tech", portal_url: "https://www.browserstack.com/careers", location: "Mumbai, India / Remote" },
  { name: "Zoho", category: "india_tech", portal_url: "https://www.zoho.com/careers/", location: "Chennai / Tenkasi, India" },
  { name: "Walmart Global Tech India", category: "india_tech", portal_url: "https://careers.walmart.com", location: "Bengaluru / Chennai, India" },
  { name: "Lowe's India", category: "india_tech", portal_url: "https://lowes.co.in/careers/", location: "Bengaluru, India" },
  { name: "DE Shaw India", category: "india_tech", portal_url: "https://www.deshawindia.com/careers", location: "Hyderabad, India" },
  { name: "Tower Research Capital India", category: "india_tech", portal_url: "https://www.tower-research.com/careers", location: "Gurgaon, India" },
  { name: "HRT India", category: "india_tech", portal_url: "https://www.hudsonrivertrading.com/careers/", location: "Gurgaon, India" },
  { name: "Graviton Research Capital", category: "india_tech", portal_url: "https://www.graviton.com/careers", location: "Gurgaon, India" }
];
