export interface SeedCompany {
  name: string;
  category: "company" | "startup" | "remote" | "visa_remote" | "india_tech" | "ai_yc";
  portal_url: string;
  location?: string;
  job_title?: string;
  actively_hiring?: boolean;
  visa_sponsorship?: boolean;
}

export const TOP_COMPANIES: SeedCompany[] = [
  // --- TOP 100 TECH COMPANIES ---
  { name: "Google", category: "company", portal_url: "https://careers.google.com", location: "Mountain View, CA / Remote" },
  { name: "Microsoft", category: "company", portal_url: "https://careers.microsoft.com", location: "Redmond, WA / Remote" },
  { name: "Apple", category: "company", portal_url: "https://www.apple.com/careers", location: "Cupertino, CA" },
  { name: "Amazon", category: "company", portal_url: "https://www.amazon.jobs", location: "Seattle, WA / Remote" },
  { name: "Meta", category: "company", portal_url: "https://www.metacareers.com", location: "Menlo Park, CA / Remote" },
  { name: "Netflix", category: "company", portal_url: "https://jobs.netflix.com", location: "Los Gatos, CA / Remote" },
  { name: "Nvidia", category: "company", portal_url: "https://www.nvidia.com/en-us/about-nvidia/careers/", location: "Santa Clara, CA" },
  { name: "Adobe", category: "company", portal_url: "https://www.adobe.com/careers.html", location: "San Jose, CA / Remote" },
  { name: "Salesforce", category: "company", portal_url: "https://www.salesforce.com/company/careers/", location: "San Francisco, CA / Remote" },
  { name: "Oracle", category: "company", portal_url: "https://www.oracle.com/careers/", location: "Austin, TX / Remote" },
  { name: "IBM", category: "company", portal_url: "https://www.ibm.com/careers", location: "Armonk, NY / Remote" },
  { name: "Cisco", category: "company", portal_url: "https://jobs.cisco.com", location: "San Jose, CA / Remote" },
  { name: "Intel", category: "company", portal_url: "https://jobs.intel.com", location: "Santa Clara, CA / Remote" },
  { name: "AMD", category: "company", portal_url: "https://www.amd.com/en/corporate/careers.html", location: "Santa Clara, CA / Remote" },
  { name: "Qualcomm", category: "company", portal_url: "https://www.qualcomm.com/company/careers", location: "San Diego, CA / Remote" },
  { name: "Uber", category: "company", portal_url: "https://www.uber.com/us/en/careers/", location: "San Francisco, CA / Remote" },
  { name: "Airbnb", category: "company", portal_url: "https://careers.airbnb.com", location: "San Francisco, CA / Remote" },
  { name: "Lyft", category: "company", portal_url: "https://www.lyft.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Spotify", category: "company", portal_url: "https://www.lifeatspotify.com", location: "Stockholm / NYC / Remote" },
  { name: "Tesla", category: "company", portal_url: "https://www.tesla.com/careers", location: "Palo Alto, CA / Austin, TX" },
  { name: "Block (Square)", category: "company", portal_url: "https://block.xyz/careers", location: "San Francisco, CA / Remote" },
  { name: "PayPal", category: "company", portal_url: "https://crafted.paypal.com/careers", location: "San Jose, CA / Remote" },
  { name: "Shopify", category: "company", portal_url: "https://www.shopify.com/careers", location: "Ottawa, ON / Remote" },
  { name: "Snowflake", category: "company", portal_url: "https://www.snowflake.com/careers/", location: "Bozeman, MT / Remote" },
  { name: "Databricks", category: "company", portal_url: "https://www.databricks.com/company/careers", location: "San Francisco, CA / Remote", actively_hiring: true },
  { name: "Palantir", category: "company", portal_url: "https://www.palantir.com/careers/", location: "Denver, CO / NYC / Remote" },
  { name: "Atlassian", category: "company", portal_url: "https://www.atlassian.com/company/careers", location: "Sydney / SF / Remote" },
  { name: "Workday", category: "company", portal_url: "https://www.workday.com/en-us/company/careers.html", location: "Pleasanton, CA / Remote" },
  { name: "ServiceNow", category: "company", portal_url: "https://www.servicenow.com/company/careers.html", location: "Santa Clara, CA / Remote" },
  { name: "Twilio", category: "company", portal_url: "https://www.twilio.com/en-us/company/jobs", location: "San Francisco, CA / Remote" },
  { name: "Cloudflare", category: "company", portal_url: "https://www.cloudflare.com/careers/", location: "San Francisco, CA / Remote", actively_hiring: true },
  { name: "Datadog", category: "company", portal_url: "https://www.datadoghq.com/careers/", location: "New York, NY / Remote" },
  { name: "MongoDB", category: "company", portal_url: "https://www.mongodb.com/careers", location: "New York, NY / Remote" },
  { name: "CrowdStrike", category: "company", portal_url: "https://www.crowdstrike.com/careers/", location: "Austin, TX / Remote" },
  { name: "Palo Alto Networks", category: "company", portal_url: "https://jobs.paloaltonetworks.com", location: "Santa Clara, CA / Remote" },
  { name: "Okta", category: "company", portal_url: "https://www.okta.com/company/careers/", location: "San Francisco, CA / Remote" },
  { name: "Splunk", category: "company", portal_url: "https://www.splunk.com/en_us/careers.html", location: "San Francisco, CA / Remote" },
  { name: "HashiCorp", category: "company", portal_url: "https://www.hashicorp.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Fastly", category: "company", portal_url: "https://www.fastly.com/careers", location: "San Francisco, CA / Remote" },
  { name: "GitLab", category: "company", portal_url: "https://about.gitlab.com/jobs/", location: "100% Remote" },
  { name: "GitHub", category: "company", portal_url: "https://github.com/about/careers", location: "San Francisco, CA / Remote" },
  { name: "Zoom", category: "company", portal_url: "https://careers.zoom.us", location: "San Jose, CA / Remote" },
  { name: "Slack", category: "company", portal_url: "https://slack.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Pinterest", category: "company", portal_url: "https://www.pinterestcareers.com", location: "San Francisco, CA / Remote" },
  { name: "Snap Inc.", category: "company", portal_url: "https://careers.snap.com", location: "Santa Monica, CA / Remote" },
  { name: "Reddit", category: "company", portal_url: "https://www.redditinc.com/careers", location: "San Francisco, CA / Remote" },
  { name: "Robinhood", category: "company", portal_url: "https://robinhood.com/us/en/careers/", location: "Menlo Park, CA / Remote" },
  { name: "Coinbase", category: "company", portal_url: "https://www.coinbase.com/careers", location: "100% Remote" },
  { name: "DoorDash", category: "company", portal_url: "https://careers.doordash.com", location: "San Francisco, CA / Remote" },
  { name: "Instacart", category: "company", portal_url: "https://instacart.careers", location: "San Francisco, CA / Remote" },
  { name: "eBay", category: "company", portal_url: "https://careers.ebayinc.com", location: "San Jose, CA / Remote" },
  { name: "Etsy", category: "company", portal_url: "https://careers.etsy.com", location: "Brooklyn, NY / Remote" },

  // --- 100+ AI STARTUPS & YC STARTUPS (ACTIVELY HIRING) ---
  { name: "OpenAI", category: "ai_yc", portal_url: "https://openai.com/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Python Backend & AI Infrastructure Engineer" },
  { name: "Anthropic", category: "ai_yc", portal_url: "https://www.anthropic.com/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Backend Engineer - AI Safety & Systems" },
  { name: "Cursor (Anysphere)", category: "ai_yc", portal_url: "https://www.cursor.com/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Backend / Systems Engineer (AI Code Assistant)" },
  { name: "Perplexity AI", category: "ai_yc", portal_url: "https://www.perplexity.ai/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Backend Engineer - Search & LLM Infrastructure" },
  { name: "Scale AI", category: "ai_yc", portal_url: "https://scale.com/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Python Backend Engineer - Data & AI Platform" },
  { name: "Cohere", category: "ai_yc", portal_url: "https://cohere.com/careers", location: "Toronto / SF / Remote", actively_hiring: true, job_title: "Backend Engineer - Enterprise LLM Serving" },
  { name: "Mistral AI", category: "ai_yc", portal_url: "https://mistral.ai/careers", location: "Paris / SF / Remote", actively_hiring: true, job_title: "Python Backend Engineer - Open AI Models" },
  { name: "Midjourney", category: "ai_yc", portal_url: "https://www.midjourney.com/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Backend Engineer - Generative Media Platform" },
  { name: "Runway", category: "ai_yc", portal_url: "https://runwayml.com/careers", location: "New York, NY / Remote", actively_hiring: true, job_title: "Python Backend Engineer - Video AI Models" },
  { name: "Groq", category: "ai_yc", portal_url: "https://groq.com/careers", location: "Mountain View, CA / Remote", actively_hiring: true, job_title: "Backend Systems Engineer - LPU Inference Engine" },
  { name: "Together AI", category: "ai_yc", portal_url: "https://www.together.ai/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Python Backend Engineer - Distributed AI Inference" },
  { name: "Pinecone", category: "ai_yc", portal_url: "https://www.pinecone.io/careers/", location: "New York, NY / Remote", actively_hiring: true, job_title: "Backend Engineer - Vector Database Engine" },
  { name: "Weaviate", category: "ai_yc", portal_url: "https://weaviate.io/careers", location: "Amsterdam / SF / Remote", actively_hiring: true, job_title: "Python Backend Engineer - Open Source Vector Search" },
  { name: "Qdrant", category: "ai_yc", portal_url: "https://qdrant.tech/careers/", location: "Berlin / Remote", actively_hiring: true, job_title: "Backend Engineer - High Performance Vector DB" },
  { name: "LangChain", category: "ai_yc", portal_url: "https://www.langchain.com/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Python Engineer - LLM Agent Framework" },
  { name: "LlamaIndex", category: "ai_yc", portal_url: "https://www.llamaindex.ai/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Python Engineer - Data Framework for LLMs" },
  { name: "Weights & Biases", category: "ai_yc", portal_url: "https://wandb.ai/site/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Python Backend Engineer - MLOps Platform" },
  { name: "Modal", category: "ai_yc", portal_url: "https://modal.com/careers", location: "New York, NY / Remote", actively_hiring: true, job_title: "Python / Systems Engineer - Serverless Cloud for AI" },
  { name: "Baseten", category: "ai_yc", portal_url: "https://www.baseten.co/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Backend Engineer - Model Deployment Platform" },
  { name: "Replicate", category: "ai_yc", portal_url: "https://replicate.com/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Python / Go Backend Engineer - Machine Learning API" },
  { name: "ElevenLabs", category: "ai_yc", portal_url: "https://elevenlabs.io/careers", location: "New York / London / Remote", actively_hiring: true, job_title: "Python Backend Engineer - Voice AI Generation" },
  { name: "Harvey AI", category: "ai_yc", portal_url: "https://www.harvey.ai/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Python Backend Engineer - Legal LLM Platform" },
  { name: "Cognition (Devin)", category: "ai_yc", portal_url: "https://www.cognition.ai/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Backend Systems Engineer - Autonomous AI Software Engineer" },
  { name: "Poolside", category: "ai_yc", portal_url: "https://poolside.ai/careers", location: "Paris / SF / Remote", actively_hiring: true, job_title: "Python Backend Engineer - Code Intelligence Models" },
  { name: "Fireworks.ai", category: "ai_yc", portal_url: "https://fireworks.ai/careers", location: "Redwood City, CA / Remote", actively_hiring: true, job_title: "Backend Engineer - Fast LLM API Engine" },
  { name: "Unstructured.io", category: "ai_yc", portal_url: "https://unstructured.io/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Python Backend Engineer - LLM Ingestion Pipeline" },
  { name: "Chroma", category: "ai_yc", portal_url: "https://www.trychroma.com/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Python / Rust Backend Engineer - Open Embedding Database" },
  { name: "Langfuse", category: "ai_yc", portal_url: "https://langfuse.com/careers", location: "Berlin / SF / Remote", actively_hiring: true, job_title: "Backend Engineer - LLM Engineering & Observability" },
  { name: "Portkey", category: "ai_yc", portal_url: "https://portkey.ai/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Backend Engineer - AI Gateway & Routing" },
  { name: "PromptLayer", category: "ai_yc", portal_url: "https://promptlayer.com/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Python Backend Engineer - Prompt Management API" },
  { name: "Helicone", category: "ai_yc", portal_url: "https://helicone.ai/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Backend Engineer - Open Source LLM Monitoring" },
  { name: "Arize AI", category: "ai_yc", portal_url: "https://arize.com/careers/", location: "Berkeley, CA / Remote", actively_hiring: true, job_title: "Python Backend Engineer - AI Observability Platform" },
  { name: "Cleanlab", category: "ai_yc", portal_url: "https://cleanlab.ai/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Python Backend Engineer - Automated Data Quality AI" },
  { name: "Hugging Face", category: "ai_yc", portal_url: "https://huggingface.co/careers", location: "NYC / Paris / Remote", actively_hiring: true, job_title: "Python Backend Engineer - Open Source Model Hub" },
  { name: "Synthesia", category: "ai_yc", portal_url: "https://www.synthesia.io/careers", location: "London, UK / Remote", actively_hiring: true, job_title: "Python Backend Engineer - AI Video Generation" },
  { name: "HeyGen", category: "ai_yc", portal_url: "https://www.heygen.com/careers", location: "Los Angeles, CA / Remote", actively_hiring: true, job_title: "Backend Engineer - AI Avatar Generation Platform" },
  { name: "Luma AI", category: "ai_yc", portal_url: "https://lumalabs.ai/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Python Backend Engineer - 3D & Video NeRF AI" },
  { name: "Pika Labs", category: "ai_yc", portal_url: "https://pika.art/careers", location: "Palo Alto, CA / Remote", actively_hiring: true, job_title: "Backend Systems Engineer - Video Generation AI" },
  { name: "Suno AI", category: "ai_yc", portal_url: "https://suno.com/careers", location: "Cambridge, MA / Remote", actively_hiring: true, job_title: "Python Backend Engineer - Music Generation AI" },
  { name: "Udio", category: "ai_yc", portal_url: "https://www.udio.com/careers", location: "New York, NY / Remote", actively_hiring: true, job_title: "Python Backend Engineer - Audio Synthesis Engine" },
  { name: "Ideogram", category: "ai_yc", portal_url: "https://ideogram.ai/careers", location: "Toronto, Canada / Remote", actively_hiring: true, job_title: "Backend Systems Engineer - Text-to-Image AI" },
  { name: "Black Forest Labs (Flux)", category: "ai_yc", portal_url: "https://blackforestlabs.ai/careers", location: "Freiburg, Germany / Remote", actively_hiring: true, job_title: "Python Backend Engineer - FLUX Image Models" },
  { name: "Mercor", category: "ai_yc", portal_url: "https://mercor.com/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Python Backend Engineer - AI Vetting & Sourcing" },
  { name: "Factory AI", category: "ai_yc", portal_url: "https://factory.ai/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Backend Systems Engineer - Autonomous Droids for Software" },
  { name: "Superhuman", category: "ai_yc", portal_url: "https://superhuman.com/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Backend Engineer - AI Email Client & Search" },
  { name: "Linear", category: "ai_yc", portal_url: "https://linear.app/careers", location: "100% Remote (US / EU)", actively_hiring: true, job_title: "Backend Systems Engineer - High Performance Issue Tracking" },
  { name: "Raycast", category: "ai_yc", portal_url: "https://www.raycast.com/careers", location: "London / Remote", actively_hiring: true, job_title: "Backend Engineer - AI Extensions & Sync Platform" },
  { name: "Warp", category: "ai_yc", portal_url: "https://www.warp.dev/careers", location: "New York, NY / Remote", actively_hiring: true, job_title: "Backend Engineer - AI-Powered Terminal Platform" },
  { name: "The Browser Company (Arc)", category: "ai_yc", portal_url: "https://browsercompany.com/careers", location: "New York, NY / Remote", actively_hiring: true, job_title: "Backend Systems Engineer - Arc Search & AI Browser" },
  { name: "Vercel", category: "ai_yc", portal_url: "https://vercel.com/careers", location: "100% Remote", actively_hiring: true, job_title: "Backend Engineer - AI SDK & Edge Compute Infrastructure" },
  { name: "Supabase", category: "ai_yc", portal_url: "https://supabase.com/careers", location: "100% Remote", actively_hiring: true, job_title: "Backend / Postgres Engineer - pgvector & AI Functions" },
  { name: "Neon", category: "ai_yc", portal_url: "https://neon.tech/careers", location: "100% Remote", actively_hiring: true, job_title: "Backend / Rust Engineer - Serverless Postgres for AI" },
  { name: "Railway", category: "ai_yc", portal_url: "https://railway.com/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Backend Engineer - Cloud Deployment Platform" },
  { name: "Render", category: "ai_yc", portal_url: "https://render.com/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Backend Engineer - Zero-DevOps Cloud" },
  { name: "Fly.io", category: "ai_yc", portal_url: "https://fly.io/jobs/", location: "100% Remote", actively_hiring: true, job_title: "Systems Engineer - Global Application Delivery & GPU Cloud" },
  { name: "Resend", category: "ai_yc", portal_url: "https://resend.com/careers", location: "100% Remote", actively_hiring: true, job_title: "Backend Engineer - Modern Email API & Transactional Engine" },
  { name: "PostHog", category: "ai_yc", portal_url: "https://posthog.com/careers", location: "100% Remote", actively_hiring: true, job_title: "Python / ClickHouse Engineer - Open Source Product Analytics" },
  { name: "Retool", category: "ai_yc", portal_url: "https://retool.com/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Backend Engineer - Internal Tools & Retool AI Platform" },
  { name: "Make", category: "ai_yc", portal_url: "https://www.make.com/en/careers", location: "Prague / Remote", actively_hiring: true, job_title: "Backend Engineer - Visual Automation & AI Workflows" },
  { name: "Zapier", category: "ai_yc", portal_url: "https://zapier.com/careers", location: "100% Remote", actively_hiring: true, job_title: "Python Backend Engineer - AI Central Automation Platform" },
  { name: "Figma", category: "ai_yc", portal_url: "https://www.figma.com/careers/", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Backend Engineer - AI Collaborative Design Tools" },
  { name: "Notion", category: "ai_yc", portal_url: "https://www.notion.so/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Backend Engineer - Notion AI & Knowledge Assistant" },
  { name: "ClickHouse", category: "ai_yc", portal_url: "https://clickhouse.com/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Backend / C++ Engineer - Real-Time Analytics DB" },
  { name: "MotherDuck", category: "ai_yc", portal_url: "https://motherduck.com/careers/", location: "Seattle, WA / Remote", actively_hiring: true, job_title: "Backend Engineer - Cloud DuckDB Analytics" },
  { name: "Milvus (Zilliz)", category: "ai_yc", portal_url: "https://zilliz.com/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Backend Engineer - Distributed Vector Database" },
  { name: "Turbopuffer", category: "ai_yc", portal_url: "https://turbopuffer.com/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Backend Engineer - Stateless Serverless Vector Search" },
  { name: "LanceDB", category: "ai_yc", portal_url: "https://lancedb.com/careers", location: "San Francisco, CA / Remote", actively_hiring: true, job_title: "Python / Rust Engineer - Embedded Vector Search Engine" },

  // --- VISA SPONSORSHIP & GLOBAL RELOCATION ---
  { name: "Adyen", category: "visa_remote", portal_url: "https://careers.adyen.com", location: "Amsterdam, Netherlands (Visa & Relocation)", visa_sponsorship: true },
  { name: "Delivery Hero", category: "visa_remote", portal_url: "https://careers.deliveryhero.com", location: "Berlin, Germany (Visa & Relocation)", visa_sponsorship: true },
  { name: "Zalando", category: "visa_remote", portal_url: "https://jobs.zalando.com", location: "Berlin, Germany (Visa & Relocation)", visa_sponsorship: true },
  { name: "Personio", category: "visa_remote", portal_url: "https://www.personio.com/careers", location: "Munich, Germany (Visa & Relocation)", visa_sponsorship: true },
  { name: "Bolt", category: "visa_remote", portal_url: "https://bolt.eu/careers/", location: "Tallinn, Estonia (Visa & Relocation)", visa_sponsorship: true },
  { name: "Shopee", category: "visa_remote", portal_url: "https://careers.shopee.sg", location: "Singapore (Visa & Relocation)", visa_sponsorship: true },
  { name: "Rakuten", category: "visa_remote", portal_url: "https://rakuten.careers", location: "Tokyo, Japan (Visa & Relocation)", visa_sponsorship: true },
  { name: "Mercari", category: "visa_remote", portal_url: "https://careers.mercari.com", location: "Tokyo, Japan (Visa & Relocation)", visa_sponsorship: true },
  { name: "LY Corporation (LINE)", category: "visa_remote", portal_url: "https://linecorp.com/en/career/", location: "Tokyo, Japan (Visa & Relocation)", visa_sponsorship: true },
  { name: "Careem", category: "visa_remote", portal_url: "https://www.careem.com/careers/", location: "Dubai, UAE (Visa & Relocation)", visa_sponsorship: true },
  { name: "Talabat", category: "visa_remote", portal_url: "https://www.talabat.com/careers", location: "Dubai, UAE (Visa & Relocation)", visa_sponsorship: true },
  { name: "Canva", category: "visa_remote", portal_url: "https://www.canva.com/careers/", location: "Sydney, Australia (Visa & Relocation)", visa_sponsorship: true },

  // --- TOP TECH & PRODUCT COMPANIES IN INDIA ---
  { name: "Flipkart", category: "india_tech", portal_url: "https://careers.flipkart.com", location: "Bengaluru, India" },
  { name: "Swiggy", category: "india_tech", portal_url: "https://careers.swiggy.com", location: "Bengaluru, India / Remote" },
  { name: "Zomato", category: "india_tech", portal_url: "https://www.zomato.com/careers", location: "Gurgaon, India" },
  { name: "Razorpay", category: "india_tech", portal_url: "https://razorpay.com/jobs/", location: "Bengaluru, India" },
  { name: "PhonePe", category: "india_tech", portal_url: "https://www.phonepe.com/careers/", location: "Bengaluru, India" },
  { name: "Paytm", category: "india_tech", portal_url: "https://paytm.com/careers", location: "Noida, India" },
  { name: "CRED", category: "india_tech", portal_url: "https://cred.club/careers", location: "Bengaluru, India" },
  { name: "Groww", category: "india_tech", portal_url: "https://groww.in/careers", location: "Bengaluru, India" },
  { name: "Zerodha", category: "india_tech", portal_url: "https://zerodha.com/careers", location: "Bengaluru, India" },
  { name: "Meesho", category: "india_tech", portal_url: "https://meesho.io/careers", location: "Bengaluru, India" },
  { name: "Oyo", category: "india_tech", portal_url: "https://www.oyorooms.com/careers", location: "Gurgaon, India" },
  { name: "Ola", category: "india_tech", portal_url: "https://www.olacabs.com/careers", location: "Bengaluru, India" },
  { name: "MakeMyTrip", category: "india_tech", portal_url: "https://careers.makemytrip.com", location: "Gurgaon, India" },
  { name: "InMobi", category: "india_tech", portal_url: "https://www.inmobi.com/company/careers/", location: "Bengaluru, India" },
  { name: "Zepto", category: "india_tech", portal_url: "https://www.zepto.co/careers", location: "Mumbai / Bengaluru, India" },
  { name: "Blinkit", category: "india_tech", portal_url: "https://blinkit.com/careers", location: "Gurgaon, India" },
  { name: "Dream11", category: "india_tech", portal_url: "https://www.dream11.com/careers", location: "Mumbai, India" },
  { name: "Freshworks", category: "india_tech", portal_url: "https://www.freshworks.com/careers/", location: "Chennai / Bengaluru, India" },
  { name: "Hasura", category: "india_tech", portal_url: "https://hasura.io/careers/", location: "Bengaluru, India / Remote" },
  { name: "BrowserStack", category: "india_tech", portal_url: "https://www.browserstack.com/careers", location: "Mumbai, India / Remote" },
  { name: "Zoho", category: "india_tech", portal_url: "https://www.zoho.com/careers/", location: "Chennai / Tenkasi, India" },
  { name: "Walmart Global Tech India", category: "india_tech", portal_url: "https://careers.walmart.com", location: "Bengaluru / Chennai, India" },
  { name: "Lowe's India", category: "india_tech", portal_url: "https://lowes.co.in/careers/", location: "Bengaluru, India" },
  { name: "DE Shaw India", category: "india_tech", portal_url: "https://www.deshawindia.com/careers", location: "Hyderabad, India" },
  { name: "Tower Research Capital India", category: "india_tech", portal_url: "https://www.tower-research.com/careers", location: "Gurgaon, India" },
  { name: "HRT India", category: "india_tech", portal_url: "https://www.hudsonrivertrading.com/careers/", location: "Gurgaon, India" },
  { name: "Graviton Research Capital", category: "india_tech", portal_url: "https://www.graviton.com/careers", location: "Gurgaon, India" }
];
